# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-16 05:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hong', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hong',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('artist_info', models.CharField(max_length=500)),
                ('cmpany', models.CharField(max_length=500)),
            ],
        ),
        migrations.RemoveField(
            model_name='choice',
            name='question',
        ),
        migrations.DeleteModel(
            name='Choice',
        ),
        migrations.DeleteModel(
            name='Question',
        ),
    ]
