# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-04 02:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hong', '0003_auto_20170416_0614'),
    ]

    operations = [
        migrations.CreateModel(
            name='Copyright',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field_id', models.CharField(blank=True, db_column='_id', max_length=50, null=True)),
                ('company_info', models.CharField(blank=True, max_length=20, null=True)),
                ('artist_info', models.CharField(blank=True, max_length=100, null=True)),
                ('site_name', models.CharField(blank=True, max_length=10, null=True)),
                ('language', models.CharField(blank=True, max_length=10, null=True)),
                ('song_info', models.CharField(blank=True, max_length=30, null=True)),
                ('url', models.CharField(blank=True, max_length=40, null=True)),
                ('company', models.CharField(blank=True, max_length=30, null=True)),
                ('company_pic', models.CharField(blank=True, max_length=50, null=True)),
                ('classify', models.CharField(blank=True, max_length=40, null=True)),
                ('date', models.CharField(blank=True, max_length=20, null=True)),
                ('album_info', models.CharField(blank=True, max_length=30, null=True)),
                ('desc', models.CharField(blank=True, max_length=500, null=True)),
            ],
            options={
                'db_table': 'copyright',
                'managed': False,
            },
        ),
        migrations.DeleteModel(
            name='Hong',
        ),
    ]
